"""MacroFlow Studio 主窗口包。

MacroFlowApp 由各功能 mixin 组合（壳层 / 助手 / 全局检测 / 守卫引擎 / 托盘 / 窗口绑定 /
录制 / 脚本与动作列表 / 执行 / 工作流 / 快捷键），对外导入面与拆分前一致：
from macroflow.ui.app import MacroFlowApp, action_summary, px, ...
"""
from __future__ import annotations

from .constants import (
    ACTION_ICONS,
    ACTION_TREE_COLUMNS,
    APP_NAME,
    APP_VERSION,
    BACKUP_INTERVAL_CHOICES,
    BACKUP_INTERVAL_MS,
    COLOR_BG,
    COLOR_BLUE,
    COLOR_BORDER,
    COLOR_FOCUS,
    COLOR_GREEN,
    COLOR_HOVER,
    COLOR_MUTED,
    COLOR_RED,
    COLOR_SIDEBAR,
    COLOR_SURFACE,
    COLOR_SURFACE_ALT,
    COLOR_TEXT,
    DEFAULT_GLOBAL_CLICK_DELAY_MS,
    EVENT_LOG_HEADER,
    FLOATING_NOTICE_HEIGHT,
    FLOATING_NOTICE_POSITIONS,
    FLOATING_NOTICE_WIDTH,
    FONT_BODY,
    FONT_BRAND,
    FONT_FAMILY,
    FONT_MONO,
    FONT_SMALL,
    FONT_SUBTITLE,
    FONT_TITLE,
    GLOBAL_TREE_COLUMNS,
    MAX_TREE_ROWS,
    MIN_MAIN_HEIGHT,
    MIN_MAIN_WIDTH,
    MODULE_CLICK_LABELS,
    RECORD_TOOLBAR_BUTTON_LABEL,
    REGION_LABELS,
    SCRIPT_CATEGORY_LABELS,
    SCRIPT_CATEGORY_VALUES,
    SEGMENT_BAR,
    TRACE_LOG_HEADER,
    WINDOWS_RUN_KEY,
    WINDOWS_RUN_VALUE,
    WORKFLOW_TREE_COLUMNS,
)
from .base import (
    _UI_SCALE,
    _key_vk,
    action_kind_label,
    apply_pointer_cursors,
    attach_autohide_scrollbar,
    bind_tree_hover,
    coordinate_scale_summary,
    default_main_geometry,
    disable_combobox_wheel_selection,
    enable_per_monitor_dpi_awareness,
    floating_notice_xy,
    pad,
    px,
    script_category_key,
    script_category_label,
    set_ui_scale,
    short_region_text,
    toolbar_spec_rows,
    workflow_execution_progress,
    workflow_script_name,
)
from .summaries import (
    _module_ref_summary,
    _module_row_result_summary,
    action_detail,
    action_summary,
    key_action_matches,
    set_matching_key_action_delays,
)
from .startup import (
    main,
    set_windows_startup,
    spawn_new_instance,
    windows_startup_command,
)

from .shell import ShellMixin
from .helpers import HelpersMixin
from .global_detect import GlobalDetectMixin
from .guards import GuardsMixin
from .tray import TrayMixin
from .window_binding import WindowBindingMixin
from .recording import RecordingMixin
from .scripts import ScriptsMixin
from .execution import ExecutionMixin
from .workflow import WorkflowMixin
from .hotkeys import HotkeysMixin

from .constants import (  # 原先由本模块导入的名字，保持可导入
    annotations,
)
from .base import (  # 原先由本模块导入的名字，保持可导入
    ACTION_ID_KEY,
    DEFAULT_MOUSE_MOVE_INTERVAL_MS,
    DEFAULT_RECORDED_SCREEN,
    DEFAULT_WORKFLOW_REPEAT_INTERVAL_MS,
    END_CURRENT_SCRIPT_LABEL,
    JUMP_TARGET_KEYS,
    MacroScript,
    NEXT_WORKFLOW_STEP_TARGET_ID,
    Path,
    RECORDED_INPUT_STEPS_KEY,
    RECORDED_INPUT_TYPE,
    SCRIPT_START_TARGET_ID,
    WindowInfo,
    Workflow,
    activate_window,
    clone_actions_with_new_ids,
    ctypes,
    ensure_action_ids,
    ensure_workflow_step_ids,
    enum_windows,
    force_english_input,
    get_cursor_pos,
    get_foreground_window_info,
    get_monitor_rect_for_window,
    get_monitor_work_area_for_point,
    get_monitor_work_area_for_window,
    get_primary_screen_rect,
    get_virtual_screen_rect,
    get_window_dpi,
    get_window_rect,
    is_current_process_window,
    is_global_script,
    is_window,
    is_window_process_foreground,
    make_window_no_activate,
    new_action_id,
    recorded_input_steps,
    script_ref_repeat_count,
    scroll_clicks,
    scroll_direction_label,
    send_button,
    send_move_absolute,
    set_dark_titlebar,
    set_rounded_window,
    show_window,
    show_window_no_activate,
    tk,
    ttk,
)
from .summaries import (  # 原先由本模块导入的名字，保持可导入
    BASE_DIR,
    DEFAULT_MODULE_NOT_FOUND_TIMEOUT_MS,
    DIRECTION_SCRIPTS_DIR,
    IMAGES_DIR,
    SCRIPTS_DIR,
    WORKFLOWS_DIR,
    archive_overwritten_script,
    available_script_path,
    backup_script,
    display_path,
    ensure_dirs,
    json,
    load_app_settings,
    load_script,
    load_workflow,
    migrate_workflow_templates,
    registered_module_object,
    registered_template_region,
    remap_hotkey_script_bindings,
    resolve_path,
    safe_name,
    save_app_settings,
    save_script,
    save_workflow,
    script_category_for_path,
    update_module_object,
)
from .startup import (  # 原先由本模块导入的名字，保持可导入
    ClickDialog,
    CloseAppDialog,
    DurationDialog,
    DurationVar,
    GameSetupNoteDialog,
    GlobalDetectDialog,
    HotkeyScriptsDialog,
    JsonActionDialog,
    JumpActionDialog,
    KeyActionDialog,
    ModulePickerDialog,
    MouseMoveDialog,
    MultiConditionClickDialog,
    OcrCompareActionDialog,
    OpenAppDialog,
    RepeatClickDialog,
    ResolutionStylesDialog,
    RowListConditionClickDialog,
    RowListDiagnosticResultDialog,
    RowRecognitionResultDialog,
    ScheduleDialog,
    ScriptDirectoriesDialog,
    ScrollDialog,
    SetResolutionActionDialog,
    TIME_UNITS,
    TemplateRegionFormDialog,
    TemplateRegionManagerDialog,
    Tooltip,
    TurnActionDialog,
    WindowPicker,
    WorkflowBatchSettingsDialog,
    WorkflowRepeatDialog,
    edit_action,
    key_to_vk,
    os,
    recorded_action_description,
    show_floating_notice,
    subprocess,
    sys,
    traceback,
    vk_to_key_name,
    workflow_step_label,
)
from .shell import (  # 原先由本模块导入的名字，保持可导入
    AdvanceToNextWorkflowStep,
    EndCurrentScriptRequest,
    FocusInputGuard,
    GuardJumpRequest,
    InputCapturer,
    JUMP_CURRENT_SCRIPT_LAST_RESULT,
    JumpToCurrentScriptLastAction,
    KeyCapturer,
    MAX_SCRIPT_REF_DEPTH,
    MacroPlayer,
    MacroRecorder,
    PlaybackStopped,
    RESERVED_HOTKEY_VKS,
    UIUpdateQueue,
    datetime,
    dialogs_ui,
    pystray,
    resolution_styles_from_settings,
    screen_template_scale,
    threading,
    tkfont,
)
from .helpers import (  # 原先由本模块导入的名字，保持可导入
    copy,
    filedialog,
    messagebox,
    re,
    simpledialog,
    time,
)
from .guards import (  # 原先由本模块导入的名字，保持可导入
    DetectionEvaluation,
    DetectionWorker,
    _get_engine,
    capture_bgr,
    find_expected_match,
    find_template,
    find_template_in_image,
    format_ocr_observation,
    matches_expected,
    ocr_match_center,
    play_alert,
    prewarm_alert,
    recognize_image_with_boxes,
    recognize_region_with_boxes,
    set_progress_callback,
    show_overlay,
)
from .tray import (  # 原先由本模块导入的名字，保持可导入
    Image,
    ImageDraw,
)
from .execution import (  # 原先由本模块导入的名字，保持可导入
    allow_display_sleep,
    keep_display_awake,
)
from .hotkeys import (  # 原先由本模块导入的名字，保持可导入
    keyboard,
)


class MacroFlowApp(ShellMixin, HelpersMixin, GlobalDetectMixin, GuardsMixin, TrayMixin, WindowBindingMixin, RecordingMixin, ScriptsMixin, ExecutionMixin, WorkflowMixin, HotkeysMixin):
    """主窗口：各功能按分节拆成 mixin，方法之间通过 self 调用。"""

